services:
  - 'docker'
language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew clean build fatjar
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=dnsh/valuestore
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO